/* 
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.  GitHub for SDKs: https://github.com/datamill-solutions 
 *
 * OpenAPI spec version: 1.6.5
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DataMill.Api;
using DataMill.Model;
using DataMill.Client;
using System.Reflection;

namespace DataMill.Test
{
    /// <summary>
    ///  Class for testing BusinessDataDunsResolveResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BusinessDataDunsResolveResponseTests
    {
        // TODO uncomment below to declare an instance variable for BusinessDataDunsResolveResponse
        //private BusinessDataDunsResolveResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BusinessDataDunsResolveResponse
            //instance = new BusinessDataDunsResolveResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BusinessDataDunsResolveResponse
        /// </summary>
        [Test]
        public void BusinessDataDunsResolveResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BusinessDataDunsResolveResponse
            //Assert.IsInstanceOfType<BusinessDataDunsResolveResponse> (instance, "variable 'instance' is a BusinessDataDunsResolveResponse");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Test]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyName2'
        /// </summary>
        [Test]
        public void CompanyName2Test()
        {
            // TODO unit test for the property 'CompanyName2'
        }
        /// <summary>
        /// Test the property 'ContinentName'
        /// </summary>
        [Test]
        public void ContinentNameTest()
        {
            // TODO unit test for the property 'ContinentName'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'CountryCode3'
        /// </summary>
        [Test]
        public void CountryCode3Test()
        {
            // TODO unit test for the property 'CountryCode3'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Test]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'FaxNumber'
        /// </summary>
        [Test]
        public void FaxNumberTest()
        {
            // TODO unit test for the property 'FaxNumber'
        }
        /// <summary>
        /// Test the property 'StateName'
        /// </summary>
        [Test]
        public void StateNameTest()
        {
            // TODO unit test for the property 'StateName'
        }
        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Test]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }
        /// <summary>
        /// Test the property 'CeoName'
        /// </summary>
        [Test]
        public void CeoNameTest()
        {
            // TODO unit test for the property 'CeoName'
        }
        /// <summary>
        /// Test the property 'CeoTitle'
        /// </summary>
        [Test]
        public void CeoTitleTest()
        {
            // TODO unit test for the property 'CeoTitle'
        }
        /// <summary>
        /// Test the property 'CeoSecondary'
        /// </summary>
        [Test]
        public void CeoSecondaryTest()
        {
            // TODO unit test for the property 'CeoSecondary'
        }
        /// <summary>
        /// Test the property 'SicCode'
        /// </summary>
        [Test]
        public void SicCodeTest()
        {
            // TODO unit test for the property 'SicCode'
        }
        /// <summary>
        /// Test the property 'SicDescription'
        /// </summary>
        [Test]
        public void SicDescriptionTest()
        {
            // TODO unit test for the property 'SicDescription'
        }
        /// <summary>
        /// Test the property 'YearStarted'
        /// </summary>
        [Test]
        public void YearStartedTest()
        {
            // TODO unit test for the property 'YearStarted'
        }
        /// <summary>
        /// Test the property 'AnnualTurnoverLocalCurrency'
        /// </summary>
        [Test]
        public void AnnualTurnoverLocalCurrencyTest()
        {
            // TODO unit test for the property 'AnnualTurnoverLocalCurrency'
        }
        /// <summary>
        /// Test the property 'AnnualTurnoverIndicatorCode'
        /// </summary>
        [Test]
        public void AnnualTurnoverIndicatorCodeTest()
        {
            // TODO unit test for the property 'AnnualTurnoverIndicatorCode'
        }
        /// <summary>
        /// Test the property 'AnnualTurnoverIndicatorDescription'
        /// </summary>
        [Test]
        public void AnnualTurnoverIndicatorDescriptionTest()
        {
            // TODO unit test for the property 'AnnualTurnoverIndicatorDescription'
        }
        /// <summary>
        /// Test the property 'AnnualTurnoverUsd'
        /// </summary>
        [Test]
        public void AnnualTurnoverUsdTest()
        {
            // TODO unit test for the property 'AnnualTurnoverUsd'
        }
        /// <summary>
        /// Test the property 'NetIncome'
        /// </summary>
        [Test]
        public void NetIncomeTest()
        {
            // TODO unit test for the property 'NetIncome'
        }
        /// <summary>
        /// Test the property 'NetIncomeUsd'
        /// </summary>
        [Test]
        public void NetIncomeUsdTest()
        {
            // TODO unit test for the property 'NetIncomeUsd'
        }
        /// <summary>
        /// Test the property 'NetWorth'
        /// </summary>
        [Test]
        public void NetWorthTest()
        {
            // TODO unit test for the property 'NetWorth'
        }
        /// <summary>
        /// Test the property 'NetWorthUsd'
        /// </summary>
        [Test]
        public void NetWorthUsdTest()
        {
            // TODO unit test for the property 'NetWorthUsd'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'CurrencyName'
        /// </summary>
        [Test]
        public void CurrencyNameTest()
        {
            // TODO unit test for the property 'CurrencyName'
        }
        /// <summary>
        /// Test the property 'MarketabilityCode'
        /// </summary>
        [Test]
        public void MarketabilityCodeTest()
        {
            // TODO unit test for the property 'MarketabilityCode'
        }
        /// <summary>
        /// Test the property 'MarketabilityDescription'
        /// </summary>
        [Test]
        public void MarketabilityDescriptionTest()
        {
            // TODO unit test for the property 'MarketabilityDescription'
        }
        /// <summary>
        /// Test the property 'TotalEmployees'
        /// </summary>
        [Test]
        public void TotalEmployeesTest()
        {
            // TODO unit test for the property 'TotalEmployees'
        }
        /// <summary>
        /// Test the property 'TotalEmployeesIndicator'
        /// </summary>
        [Test]
        public void TotalEmployeesIndicatorTest()
        {
            // TODO unit test for the property 'TotalEmployeesIndicator'
        }
        /// <summary>
        /// Test the property 'TotalEmployeesIndicatorDescription'
        /// </summary>
        [Test]
        public void TotalEmployeesIndicatorDescriptionTest()
        {
            // TODO unit test for the property 'TotalEmployeesIndicatorDescription'
        }
        /// <summary>
        /// Test the property 'TotalEmployeesPhysicalAddress'
        /// </summary>
        [Test]
        public void TotalEmployeesPhysicalAddressTest()
        {
            // TODO unit test for the property 'TotalEmployeesPhysicalAddress'
        }
        /// <summary>
        /// Test the property 'TotalEmployeesPhysicalAddressIndicator'
        /// </summary>
        [Test]
        public void TotalEmployeesPhysicalAddressIndicatorTest()
        {
            // TODO unit test for the property 'TotalEmployeesPhysicalAddressIndicator'
        }
        /// <summary>
        /// Test the property 'ImportExportIndicator'
        /// </summary>
        [Test]
        public void ImportExportIndicatorTest()
        {
            // TODO unit test for the property 'ImportExportIndicator'
        }
        /// <summary>
        /// Test the property 'ImportExportIndicatorDescription'
        /// </summary>
        [Test]
        public void ImportExportIndicatorDescriptionTest()
        {
            // TODO unit test for the property 'ImportExportIndicatorDescription'
        }
        /// <summary>
        /// Test the property 'LegalFormCode'
        /// </summary>
        [Test]
        public void LegalFormCodeTest()
        {
            // TODO unit test for the property 'LegalFormCode'
        }
        /// <summary>
        /// Test the property 'LegalFormDescription'
        /// </summary>
        [Test]
        public void LegalFormDescriptionTest()
        {
            // TODO unit test for the property 'LegalFormDescription'
        }
        /// <summary>
        /// Test the property 'BusinessStructureCode'
        /// </summary>
        [Test]
        public void BusinessStructureCodeTest()
        {
            // TODO unit test for the property 'BusinessStructureCode'
        }
        /// <summary>
        /// Test the property 'BusinessStructureDescription'
        /// </summary>
        [Test]
        public void BusinessStructureDescriptionTest()
        {
            // TODO unit test for the property 'BusinessStructureDescription'
        }
        /// <summary>
        /// Test the property 'BusinessRegistrationNumberCode'
        /// </summary>
        [Test]
        public void BusinessRegistrationNumberCodeTest()
        {
            // TODO unit test for the property 'BusinessRegistrationNumberCode'
        }
        /// <summary>
        /// Test the property 'BusinessRegistrationNumberCodeDescription'
        /// </summary>
        [Test]
        public void BusinessRegistrationNumberCodeDescriptionTest()
        {
            // TODO unit test for the property 'BusinessRegistrationNumberCodeDescription'
        }
        /// <summary>
        /// Test the property 'UndeliverableIndicator'
        /// </summary>
        [Test]
        public void UndeliverableIndicatorTest()
        {
            // TODO unit test for the property 'UndeliverableIndicator'
        }
        /// <summary>
        /// Test the property 'UndeliverableDescription'
        /// </summary>
        [Test]
        public void UndeliverableDescriptionTest()
        {
            // TODO unit test for the property 'UndeliverableDescription'
        }
        /// <summary>
        /// Test the property 'FinancialStatementDate'
        /// </summary>
        [Test]
        public void FinancialStatementDateTest()
        {
            // TODO unit test for the property 'FinancialStatementDate'
        }
        /// <summary>
        /// Test the property 'ReportDate'
        /// </summary>
        [Test]
        public void ReportDateTest()
        {
            // TODO unit test for the property 'ReportDate'
        }
        /// <summary>
        /// Test the property 'IsOnlyAvailableAddress'
        /// </summary>
        [Test]
        public void IsOnlyAvailableAddressTest()
        {
            // TODO unit test for the property 'IsOnlyAvailableAddress'
        }
        /// <summary>
        /// Test the property 'IsSubsidiary'
        /// </summary>
        [Test]
        public void IsSubsidiaryTest()
        {
            // TODO unit test for the property 'IsSubsidiary'
        }
        /// <summary>
        /// Test the property 'TotalEmployeesIncludingPrincipalsIndicator'
        /// </summary>
        [Test]
        public void TotalEmployeesIncludingPrincipalsIndicatorTest()
        {
            // TODO unit test for the property 'TotalEmployeesIncludingPrincipalsIndicator'
        }
        /// <summary>
        /// Test the property 'IsOutOfBusiness'
        /// </summary>
        [Test]
        public void IsOutOfBusinessTest()
        {
            // TODO unit test for the property 'IsOutOfBusiness'
        }

    }

}
