/* 
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.  GitHub for SDKs: https://github.com/datamill-solutions 
 *
 * OpenAPI spec version: 1.6.5
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DataMill.Api;
using DataMill.Model;
using DataMill.Client;
using System.Reflection;

namespace DataMill.Test
{
    /// <summary>
    ///  Class for testing BusinessDataDunsSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BusinessDataDunsSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for BusinessDataDunsSearchResult
        //private BusinessDataDunsSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BusinessDataDunsSearchResult
            //instance = new BusinessDataDunsSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BusinessDataDunsSearchResult
        /// </summary>
        [Test]
        public void BusinessDataDunsSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BusinessDataDunsSearchResult
            //Assert.IsInstanceOfType<BusinessDataDunsSearchResult> (instance, "variable 'instance' is a BusinessDataDunsSearchResult");
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Test]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'DunsNumber'
        /// </summary>
        [Test]
        public void DunsNumberTest()
        {
            // TODO unit test for the property 'DunsNumber'
        }
        /// <summary>
        /// Test the property 'DunsNumberHq'
        /// </summary>
        [Test]
        public void DunsNumberHqTest()
        {
            // TODO unit test for the property 'DunsNumberHq'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'BranchCode'
        /// </summary>
        [Test]
        public void BranchCodeTest()
        {
            // TODO unit test for the property 'BranchCode'
        }
        /// <summary>
        /// Test the property 'BranchDescription'
        /// </summary>
        [Test]
        public void BranchDescriptionTest()
        {
            // TODO unit test for the property 'BranchDescription'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
