/* 
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.  GitHub for SDKs: https://github.com/datamill-solutions 
 *
 * OpenAPI spec version: 1.6.5
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DataMill.Api;
using DataMill.Model;
using DataMill.Client;
using System.Reflection;

namespace DataMill.Test
{
    /// <summary>
    ///  Class for testing SocialMediaActivitiesGetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SocialMediaActivitiesGetResponseTests
    {
        // TODO uncomment below to declare an instance variable for SocialMediaActivitiesGetResponse
        //private SocialMediaActivitiesGetResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SocialMediaActivitiesGetResponse
            //instance = new SocialMediaActivitiesGetResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SocialMediaActivitiesGetResponse
        /// </summary>
        [Test]
        public void SocialMediaActivitiesGetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SocialMediaActivitiesGetResponse
            //Assert.IsInstanceOfType<SocialMediaActivitiesGetResponse> (instance, "variable 'instance' is a SocialMediaActivitiesGetResponse");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Test]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Test]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }
        /// <summary>
        /// Test the property 'Bio'
        /// </summary>
        [Test]
        public void BioTest()
        {
            // TODO unit test for the property 'Bio'
        }
        /// <summary>
        /// Test the property 'MaxFollowers'
        /// </summary>
        [Test]
        public void MaxFollowersTest()
        {
            // TODO unit test for the property 'MaxFollowers'
        }
        /// <summary>
        /// Test the property 'SumFollowers'
        /// </summary>
        [Test]
        public void SumFollowersTest()
        {
            // TODO unit test for the property 'SumFollowers'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Education'
        /// </summary>
        [Test]
        public void EducationTest()
        {
            // TODO unit test for the property 'Education'
        }
        /// <summary>
        /// Test the property 'Employment'
        /// </summary>
        [Test]
        public void EmploymentTest()
        {
            // TODO unit test for the property 'Employment'
        }
        /// <summary>
        /// Test the property 'Linkedin'
        /// </summary>
        [Test]
        public void LinkedinTest()
        {
            // TODO unit test for the property 'Linkedin'
        }
        /// <summary>
        /// Test the property 'Xing'
        /// </summary>
        [Test]
        public void XingTest()
        {
            // TODO unit test for the property 'Xing'
        }
        /// <summary>
        /// Test the property 'Facebook'
        /// </summary>
        [Test]
        public void FacebookTest()
        {
            // TODO unit test for the property 'Facebook'
        }
        /// <summary>
        /// Test the property 'Twitter'
        /// </summary>
        [Test]
        public void TwitterTest()
        {
            // TODO unit test for the property 'Twitter'
        }
        /// <summary>
        /// Test the property 'Pinterest'
        /// </summary>
        [Test]
        public void PinterestTest()
        {
            // TODO unit test for the property 'Pinterest'
        }
        /// <summary>
        /// Test the property 'Instagram'
        /// </summary>
        [Test]
        public void InstagramTest()
        {
            // TODO unit test for the property 'Instagram'
        }
        /// <summary>
        /// Test the property 'Youtube'
        /// </summary>
        [Test]
        public void YoutubeTest()
        {
            // TODO unit test for the property 'Youtube'
        }
        /// <summary>
        /// Test the property 'Googleplus'
        /// </summary>
        [Test]
        public void GoogleplusTest()
        {
            // TODO unit test for the property 'Googleplus'
        }
        /// <summary>
        /// Test the property 'Klout'
        /// </summary>
        [Test]
        public void KloutTest()
        {
            // TODO unit test for the property 'Klout'
        }

    }

}
