/* 
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.  GitHub for SDKs: https://github.com/datamill-solutions 
 *
 * OpenAPI spec version: 1.6.5
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DataMill.Api;
using DataMill.Model;
using DataMill.Client;
using System.Reflection;

namespace DataMill.Test
{
    /// <summary>
    ///  Class for testing SocialMediaActivitiesGetInstagram
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SocialMediaActivitiesGetInstagramTests
    {
        // TODO uncomment below to declare an instance variable for SocialMediaActivitiesGetInstagram
        //private SocialMediaActivitiesGetInstagram instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SocialMediaActivitiesGetInstagram
            //instance = new SocialMediaActivitiesGetInstagram();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SocialMediaActivitiesGetInstagram
        /// </summary>
        [Test]
        public void SocialMediaActivitiesGetInstagramInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SocialMediaActivitiesGetInstagram
            //Assert.IsInstanceOfType<SocialMediaActivitiesGetInstagram> (instance, "variable 'instance' is a SocialMediaActivitiesGetInstagram");
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Bio'
        /// </summary>
        [Test]
        public void BioTest()
        {
            // TODO unit test for the property 'Bio'
        }
        /// <summary>
        /// Test the property 'Followers'
        /// </summary>
        [Test]
        public void FollowersTest()
        {
            // TODO unit test for the property 'Followers'
        }
        /// <summary>
        /// Test the property 'IsPrivate'
        /// </summary>
        [Test]
        public void IsPrivateTest()
        {
            // TODO unit test for the property 'IsPrivate'
        }
        /// <summary>
        /// Test the property 'Posts'
        /// </summary>
        [Test]
        public void PostsTest()
        {
            // TODO unit test for the property 'Posts'
        }
        /// <summary>
        /// Test the property 'Engagement'
        /// </summary>
        [Test]
        public void EngagementTest()
        {
            // TODO unit test for the property 'Engagement'
        }
        /// <summary>
        /// Test the property 'EngagementPercent'
        /// </summary>
        [Test]
        public void EngagementPercentTest()
        {
            // TODO unit test for the property 'EngagementPercent'
        }

    }

}
