/* 
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market. 
 *
 * OpenAPI spec version: 1.6.4
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DataMill.Model
{
    /// <summary>
    /// Response of successful transformation request for /business-data/duns/search
    /// </summary>
    [DataContract]
    public partial class BusinessDataDunsSearchResponse :  IEquatable<BusinessDataDunsSearchResponse>, IValidatableObject
    {
        /// <summary>
        /// Short description about the number of results found: **no result**: Could not find any company which matches the specified criteria, **single result**: We found 1 company which matches the specified criteria, **multiple results**: We found at least 2 companies which matches the specified criteria 
        /// </summary>
        /// <value>Short description about the number of results found: **no result**: Could not find any company which matches the specified criteria, **single result**: We found 1 company which matches the specified criteria, **multiple results**: We found at least 2 companies which matches the specified criteria </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum Noresult for "no result"
            /// </summary>
            [EnumMember(Value = "no result")]
            Noresult,
            
            /// <summary>
            /// Enum Singleresult for "single result"
            /// </summary>
            [EnumMember(Value = "single result")]
            Singleresult,
            
            /// <summary>
            /// Enum Multipleresults for "multiple results"
            /// </summary>
            [EnumMember(Value = "multiple results")]
            Multipleresults
        }

        /// <summary>
        /// Short description about the number of results found: **no result**: Could not find any company which matches the specified criteria, **single result**: We found 1 company which matches the specified criteria, **multiple results**: We found at least 2 companies which matches the specified criteria 
        /// </summary>
        /// <value>Short description about the number of results found: **no result**: Could not find any company which matches the specified criteria, **single result**: We found 1 company which matches the specified criteria, **multiple results**: We found at least 2 companies which matches the specified criteria </value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessDataDunsSearchResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BusinessDataDunsSearchResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessDataDunsSearchResponse" /> class.
        /// </summary>
        /// <param name="Status">Short description about the number of results found: **no result**: Could not find any company which matches the specified criteria, **single result**: We found 1 company which matches the specified criteria, **multiple results**: We found at least 2 companies which matches the specified criteria  (required).</param>
        /// <param name="Results">Collection of all found companies (required).</param>
        public BusinessDataDunsSearchResponse(StatusEnum? Status = null, List<BusinessDataDunsSearchResult> Results = null)
        {
            // to ensure "Status" is required (not null)
            if (Status == null)
            {
                throw new InvalidDataException("Status is a required property for BusinessDataDunsSearchResponse and cannot be null");
            }
            else
            {
                this.Status = Status;
            }
            // to ensure "Results" is required (not null)
            if (Results == null)
            {
                throw new InvalidDataException("Results is a required property for BusinessDataDunsSearchResponse and cannot be null");
            }
            else
            {
                this.Results = Results;
            }
        }
        
        /// <summary>
        /// Collection of all found companies
        /// </summary>
        /// <value>Collection of all found companies</value>
        [DataMember(Name="results", EmitDefaultValue=false)]
        public List<BusinessDataDunsSearchResult> Results { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessDataDunsSearchResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BusinessDataDunsSearchResponse);
        }

        /// <summary>
        /// Returns true if BusinessDataDunsSearchResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of BusinessDataDunsSearchResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessDataDunsSearchResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Results == other.Results ||
                    this.Results != null &&
                    this.Results.SequenceEqual(other.Results)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.Results != null)
                    hash = hash * 59 + this.Results.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
