/* 
 * /data.mill for applications
 *
 * **&#47;data.mill for applications** is the most versatile and powerful API for all aspects of data quality in your business application.  Use **&#47;data.mill** to check, correct and enrich personal data and business information. The internationally applicable functions can be integrated easily into existing applications, whether desktop, online or mobile and thus enable you to professionally improve your customer or supplier database, directly in your system. Due to **&#47;data.mill**'s pay-per-use credit model there are no setup fees or fixed monthly subscription fees.  **&#47;data.mill** is constantly evolving and upgraded with the latest technology and data services available on the market.  GitHub for SDKs: https://github.com/datamill-solutions 
 *
 * OpenAPI spec version: 1.6.5
 * Contact: info@datamill.solutions
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DataMill.Model
{
    /// <summary>
    /// Response of successful transformation request for /phonetic/code/get
    /// </summary>
    [DataContract]
    public partial class PhoneticCodeGetResponse :  IEquatable<PhoneticCodeGetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhoneticCodeGetResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PhoneticCodeGetResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PhoneticCodeGetResponse" /> class.
        /// </summary>
        /// <param name="PhoneticCodes">The phonetic codes for each word of the input text  (required).</param>
        public PhoneticCodeGetResponse(List<string> PhoneticCodes = null)
        {
            // to ensure "PhoneticCodes" is required (not null)
            if (PhoneticCodes == null)
            {
                throw new InvalidDataException("PhoneticCodes is a required property for PhoneticCodeGetResponse and cannot be null");
            }
            else
            {
                this.PhoneticCodes = PhoneticCodes;
            }
        }
        
        /// <summary>
        /// The phonetic codes for each word of the input text 
        /// </summary>
        /// <value>The phonetic codes for each word of the input text </value>
        [DataMember(Name="phonetic_codes", EmitDefaultValue=false)]
        public List<string> PhoneticCodes { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhoneticCodeGetResponse {\n");
            sb.Append("  PhoneticCodes: ").Append(PhoneticCodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PhoneticCodeGetResponse);
        }

        /// <summary>
        /// Returns true if PhoneticCodeGetResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of PhoneticCodeGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhoneticCodeGetResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PhoneticCodes == other.PhoneticCodes ||
                    this.PhoneticCodes != null &&
                    this.PhoneticCodes.SequenceEqual(other.PhoneticCodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PhoneticCodes != null)
                    hash = hash * 59 + this.PhoneticCodes.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
